### ISSUE TITLE
Straighten images repos

### ISSUE THREAD

**Issue by hoegaarden** [vmware-tanzu/tanzu-application-platform-reference-service-packages#16]
For our image repos, we are currently using (at least):

- ghcr.io/vmware-tanzu/tanzu-application-platform-reference-packages/psql.aws.references.services.apps.tanzu.vmware.com
- ghcr.io/vmware-tanzu/tanzu-application-platform-reference-packages/psql.google.references.services.apps.tanzu.vmware.com
- ghcr.io/vmware-tanzu/tanzu-application-platform-reference-packages/tap-service-reference-package-repo:0.0.1

Now, that the repo has its final name we should:
- rename those: `vmware-tanzu/tanzu-application-platform-reference-packages => vmware-tanzu/tanzu-application-platform-reference-service-packages`
- make sure they are "connected" to this git repo (and not leave them "floating" in the org), to allow all of use to manage those, push tag to them, ...

**Comment by teddyking** [comment]
Rather than renaming the existing images it might make sense to just push new images with the new names (in case anyone is depending on any of the existing names).
